### ISSUE TITLE
Build Failed: op3_gui_demo

### ISSUE THREAD

**Issue by robograffitti** [ROBOTIS-GIT/ROBOTIS-OP3-Tools#3]
Build failed with op3_gui_demo because there are no packages such as op3_online_walking_module and op3_online_walking_module_msgs in this organization ROBOTIS-GIT.

How can I get this new walking package?

robotis@ROBOTIS-JAPAN05:~/robotis_ws$ catkin b op3_gui_demo
==> Expanding alias 'b' from 'catkin b op3_gui_demo' to 'catkin build op3_gui_demo'
-------------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/kinetic
Workspace:                   /home/robotis/robotis_ws
-------------------------------------------------------------
Source Space:       [exists] /home/robotis/robotis_ws/src
Log Space:          [exists] /home/robotis/robotis_ws/logs
Build Space:        [exists] /home/robotis/robotis_ws/build
Devel Space:        [exists] /home/robotis/robotis_ws/devel
Install Space:      [unused] /home/robotis/robotis_ws/install
DESTDIR:            [unused] None
-------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
-------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-------------------------------------------------------------
Workspace configuration appears valid.
-------------------------------------------------------------
[build] Found '63' packages in 0.0 seconds.                                                                                        
[build] Package table is up to date.                                                                                               
Starting  >>> op3_walking_module_msgs                                                                                              
Starting  >>> robotis_controller_msgs                                                                                              
Finished  <<< op3_walking_module_msgs                [ 0.2 seconds ]                                                               
Finished  <<< robotis_controller_msgs                [ 0.2 seconds ]                                                               
Starting  >>> op3_gui_demo                                                                                                         
No handlers could be found for logger "trollius"d] [op3_gui_demo:check - 0.4]                                                      
___________________________________________________________________________________________________________________________________
Errors     << op3_gui_demo:check /home/robotis/robotis_ws/logs/op3_gui_demo/build.check.009.log                                    
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by
  "op3_online_walking_module_msgs" with any of the following names:

    op3_online_walking_module_msgsConfig.cmake
    op3_online_walking_module_msgs-config.cmake

  Add the installation prefix of "op3_online_walking_module_msgs" to
  CMAKE_PREFIX_PATH or set "op3_online_walking_module_msgs_DIR" to a
  directory containing one of the above files.  If
  "op3_online_walking_module_msgs" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:13 (find_package)

CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by
  "op3_online_walking_module_msgs" with any of the following names:

    op3_online_walking_module_msgsConfig.cmake
    op3_online_walking_module_msgs-config.cmake

  Add the installation prefix of "op3_online_walking_module_msgs" to
  CMAKE_PREFIX_PATH or set "op3_online_walking_module_msgs_DIR" to a
  directory containing one of the above files.  If
  "op3_online_walking_module_msgs" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:13 (find_package)

cd /home/robotis/robotis_ws/build/op3_gui_demo; catkin build --get-env op3_gui_demo | catkin env -si  /usr/bin/make cmake_check_build_system; cd -
...................................................................................................................................
Failed     << op3_gui_demo:check                     [ Exited with code 2 ]                                                        
Failed    <<< op3_gui_demo                           [ 0.5 seconds ]                                                               
[build] Summary: 2 of 3 packages succeeded.                                                                                        
[build]   Ignored:   60 packages were skipped or are blacklisted.                                                                  
[build]   Warnings:  None.                                                                                                         
[build]   Abandoned: None.                                                                                                         
[build]   Failed:    1 packages failed.                                                                                            
[build] Runtime: 1.0 seconds total.

**Comment by kaym9n** [comment]
I'm sorry for your inconvenience.
I just pushed the last source for online_walking to a remote git.
(https://github.com/ROBOTIS-GIT/ROBOTIS-OP3/pull/26)

**Comment by robograffitti** [comment]
You also need to update ROBOTIS-Framework because of the following errors:

robotis@ROBOTIS-JAPAN05:~/robotis_ws$ catkin b op3_online_walking_module --force-cmake
==> Expanding alias 'b' from 'catkin b op3_online_walking_module --force-cmake' to 'catkin build op3_online_walking_module --force-cmake'
-------------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/kinetic
Workspace:                   /home/robotis/robotis_ws
-------------------------------------------------------------
Source Space:       [exists] /home/robotis/robotis_ws/src
Log Space:          [exists] /home/robotis/robotis_ws/logs
Build Space:        [exists] /home/robotis/robotis_ws/build
Devel Space:        [exists] /home/robotis/robotis_ws/devel
Install Space:      [unused] /home/robotis/robotis_ws/install
DESTDIR:            [unused] None
-------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
-------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-------------------------------------------------------------
Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
-------------------------------------------------------------
[build] Found '69' packages in 0.0 seconds.                                                                                                                                                    
[build] Package table is up to date.                                                                                                                                                           
Starting  >>> dynamixel_sdk                                                                                                                                                                    
Starting  >>> op3_online_walking_module_msgs                                                                                                                                                   
Starting  >>> robotis_math                                                                                                                                                                     
Finished  <<< robotis_math                                  [ 0.7 seconds ]                                                                                                                    
Starting  >>> op3_balance_control                                                                                                                                                              
Finished  <<< dynamixel_sdk                                 [ 0.7 seconds ]                                                                                                                    
Starting  >>> robotis_device                                                                                                                                                                   
Finished  <<< op3_online_walking_module_msgs                [ 1.1 seconds ]                                                                                                                    
_______________________________________________________________________________________________________________________________________________________________________________________________
Warnings   << op3_balance_control:cmake /home/robotis/robotis_ws/logs/op3_balance_control/build.cmake.002.log                                                                                  
CMake Warning at /opt/ros/kinetic/share/cmake_modules/cmake/Modules/FindEigen.cmake:62 (message):
  The FindEigen.cmake Module in the cmake_modules package is deprecated.

  Please use the FindEigen3.cmake Module provided with Eigen.  Change
  instances of find_package(Eigen) to find_package(Eigen3).  Check the
  FindEigen3.cmake Module for the resulting CMake variable names.

Call Stack (most recent call first):
  CMakeLists.txt:15 (find_package)


cd /home/robotis/robotis_ws/build/op3_balance_control; catkin build --get-env op3_balance_control | catkin env -si  /usr/bin/cmake /home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_balance_control --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/robotis/robotis_ws/devel/.private/op3_balance_control -DCMAKE_INSTALL_PREFIX=/home/robotis/robotis_ws/install; cd -
...............................................................................................................................................................................................
Finished  <<< op3_balance_control                           [ 0.8 seconds ]                                                                                                                    
Finished  <<< robotis_device                                [ 0.7 seconds ]                                                                                                                    
Starting  >>> robotis_framework_common                                                                                                                                                         
Finished  <<< robotis_framework_common                      [ 0.6 seconds ]                                                                                                                    
Starting  >>> op3_online_walking_module                                                                                                                                                        
_______________________________________________________________________________________________________________________________________________________________________________________________
Warnings   << op3_online_walking_module:cmake /home/robotis/robotis_ws/logs/op3_online_walking_module/build.cmake.002.log                                                                      
CMake Warning at /opt/ros/kinetic/share/cmake_modules/cmake/Modules/FindEigen.cmake:62 (message):
  The FindEigen.cmake Module in the cmake_modules package is deprecated.

  Please use the FindEigen3.cmake Module provided with Eigen.  Change
  instances of find_package(Eigen) to find_package(Eigen3).  Check the
  FindEigen3.cmake Module for the resulting CMake variable names.

Call Stack (most recent call first):
  CMakeLists.txt:20 (find_package)


cd /home/robotis/robotis_ws/build/op3_online_walking_module; catkin build --get-env op3_online_walking_module | catkin env -si  /usr/bin/cmake /home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/robotis/robotis_ws/devel/.private/op3_online_walking_module -DCMAKE_INSTALL_PREFIX=/home/robotis/robotis_ws/install; cd -
...............................................................................................................................................................................................
_______________________________________________________________________________________________________________________________________________________________________________________________
Errors     << op3_online_walking_module:make /home/robotis/robotis_ws/logs/op3_online_walking_module/build.make.008.log                                                                        
In file included from /home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/wholebody_control.cpp:20:0:
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/include/op3_online_walking_module/wholebody_control.h:66:22: error: ‘MinimumJerk’ in namespace ‘robotis_framework’ does not name a type
   robotis_framework::MinimumJerk *task_trajectory_;
                      ^
In file included from /home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/walking_control.cpp:20:0:
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/include/op3_online_walking_module/walking_control.h:110:22: error: ‘MinimumJerk’ in namespace ‘robotis_framework’ does not name a type
   robotis_framework::MinimumJerk *body_trajectory_;
                      ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/include/op3_online_walking_module/walking_control.h:111:22: error: ‘MinimumJerkViaPoint’ in namespace ‘robotis_framework’ does not name a type
   robotis_framework::MinimumJerkViaPoint *r_foot_tra_;
                      ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/include/op3_online_walking_module/walking_control.h:112:22: error: ‘MinimumJerkViaPoint’ in namespace ‘robotis_framework’ does not name a type
   robotis_framework::MinimumJerkViaPoint *l_foot_tra_;
                      ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/include/op3_online_walking_module/walking_control.h:114:22: error: ‘PreviewControl’ in namespace ‘robotis_framework’ does not name a type
   robotis_framework::PreviewControl *preview_control_;
                      ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/wholebody_control.cpp: In member function ‘void WholebodyControl::initialize(std::vector<double>, std::vector<double>, std::vector<double>, std::vector<double>, std::vector<double>, std::vector<double>)’:
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/wholebody_control.cpp:109:5: error: ‘task_trajectory_’ was not declared in this scope
     task_trajectory_ =
     ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/wholebody_control.cpp:110:13: error: expected type-specifier
         new robotis_framework::MinimumJerk(init_time_, fin_time_,
             ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/wholebody_control.cpp:117:5: error: ‘task_trajectory_’ was not declared in this scope
     task_trajectory_ =
     ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/wholebody_control.cpp:118:13: error: expected type-specifier
         new robotis_framework::MinimumJerk(init_time_, fin_time_,
             ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/wholebody_control.cpp:125:5: error: ‘task_trajectory_’ was not declared in this scope
     task_trajectory_ =
     ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/wholebody_control.cpp:126:13: error: expected type-specifier
         new robotis_framework::MinimumJerk(init_time_, fin_time_,
             ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/wholebody_control.cpp: In member function ‘void WholebodyControl::finalize()’:
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/wholebody_control.cpp:140:10: error: ‘task_trajectory_’ was not declared in this scope
   delete task_trajectory_;
          ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/wholebody_control.cpp: In member function ‘void WholebodyControl::set(double)’:
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/wholebody_control.cpp:145:40: error: ‘task_trajectory_’ was not declared in this scope
   std::vector<double_t> des_task_pos = task_trajectory_->getPosition(time);
                                        ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/walking_control.cpp: In member function ‘void WalkingControl::calcFootTrajectory(int)’:
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/walking_control.cpp:549:5: error: ‘l_foot_tra_’ was not declared in this scope
     l_foot_tra_ = new robotis_framework::MinimumJerkViaPoint(init_time_, fin_time_, via_time, dsp_ratio_,
     ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/walking_control.cpp:549:23: error: expected type-specifier
     l_foot_tra_ = new robotis_framework::MinimumJerkViaPoint(init_time_, fin_time_, via_time, dsp_ratio_,
                       ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/walking_control.cpp:597:5: error: ‘r_foot_tra_’ was not declared in this scope
     r_foot_tra_ = new robotis_framework::MinimumJerkViaPoint(init_time_, fin_time_, via_time, dsp_ratio_,
     ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/walking_control.cpp:597:23: error: expected type-specifier
     r_foot_tra_ = new robotis_framework::MinimumJerkViaPoint(init_time_, fin_time_, via_time, dsp_ratio_,
                       ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/walking_control.cpp: In member function ‘void WalkingControl::calcFootStepPose(double, int)’:
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/walking_control.cpp:613:23: error: ‘l_foot_tra_’ was not declared in this scope
     des_l_foot_pos_ = l_foot_tra_->getPosition(time);
                       ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/walking_control.cpp:627:23: error: ‘r_foot_tra_’ was not declared in this scope
     des_r_foot_pos_ = r_foot_tra_->getPosition(time);
                       ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/walking_control.cpp: In member function ‘void WalkingControl::calcPreviewParam(op3_online_walking_module_msgs::PreviewResponse)’:
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/walking_control.cpp:828:3: error: ‘preview_control_’ was not declared in this scope
   preview_control_ = new robotis_framework::PreviewControl();
   ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/walking_control.cpp:828:26: error: expected type-specifier
   preview_control_ = new robotis_framework::PreviewControl();
                          ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/walking_control.cpp:834:10: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
   delete preview_control_;
          ^
make[2]: *** [CMakeFiles/op3_online_walking_module.dir/src/wholebody_control.cpp.o] エラー 1
make[2]: *** 未完了のジョブを待っています....
make[2]: *** [CMakeFiles/op3_online_walking_module.dir/src/walking_control.cpp.o] エラー 1
In file included from /home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/include/op3_online_walking_module/online_walking_module.h:38:0,
                 from /home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp:19:
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/include/op3_online_walking_module/wholebody_control.h:66:22: error: ‘MinimumJerk’ in namespace ‘robotis_framework’ does not name a type
   robotis_framework::MinimumJerk *task_trajectory_;
                      ^
In file included from /home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/include/op3_online_walking_module/online_walking_module.h:39:0,
                 from /home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp:19:
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/include/op3_online_walking_module/walking_control.h:110:22: error: ‘MinimumJerk’ in namespace ‘robotis_framework’ does not name a type
   robotis_framework::MinimumJerk *body_trajectory_;
                      ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/include/op3_online_walking_module/walking_control.h:111:22: error: ‘MinimumJerkViaPoint’ in namespace ‘robotis_framework’ does not name a type
   robotis_framework::MinimumJerkViaPoint *r_foot_tra_;
                      ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/include/op3_online_walking_module/walking_control.h:112:22: error: ‘MinimumJerkViaPoint’ in namespace ‘robotis_framework’ does not name a type
   robotis_framework::MinimumJerkViaPoint *l_foot_tra_;
                      ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/include/op3_online_walking_module/walking_control.h:114:22: error: ‘PreviewControl’ in namespace ‘robotis_framework’ does not name a type
   robotis_framework::PreviewControl *preview_control_;
                      ^
In file included from /home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp:19:0:
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/include/op3_online_walking_module/online_walking_module.h:191:22: error: ‘MinimumJerk’ in namespace ‘robotis_framework’ does not name a type
   robotis_framework::MinimumJerk *joint_tra_;
                      ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/include/op3_online_walking_module/online_walking_module.h:192:22: error: ‘MinimumJerk’ in namespace ‘robotis_framework’ does not name a type
   robotis_framework::MinimumJerk *balance_tra_;
                      ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/include/op3_online_walking_module/online_walking_module.h:193:22: error: ‘MinimumJerk’ in namespace ‘robotis_framework’ does not name a type
   robotis_framework::MinimumJerk *body_offset_tra_;
                      ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/include/op3_online_walking_module/online_walking_module.h:194:22: error: ‘MinimumJerkViaPoint’ in namespace ‘robotis_framework’ does not name a type
   robotis_framework::MinimumJerkViaPoint *feed_forward_tra_;
                      ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp: In member function ‘void robotis_op::OnlineWalkingModule::initBalanceControl()’:
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp:437:3: error: ‘balance_tra_’ was not declared in this scope
   balance_tra_ =
   ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp:438:11: error: expected type-specifier
       new robotis_framework::MinimumJerk(ini_time, mov_time,
           ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp: In member function ‘void robotis_op::OnlineWalkingModule::calcBalanceControl()’:
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp:456:31: error: ‘balance_tra_’ was not declared in this scope
     des_balance_gain_ratio_ = balance_tra_->getPosition(cur_time);
                               ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp:462:14: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
       delete balance_tra_;
              ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp: In member function ‘void robotis_op::OnlineWalkingModule::initJointControl()’:
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp:620:3: error: ‘joint_tra_’ was not declared in this scope
   joint_tra_ =
   ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp:621:11: error: expected type-specifier
       new robotis_framework::MinimumJerk(ini_time, mov_time,
           ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp: In member function ‘void robotis_op::OnlineWalkingModule::calcJointControl()’:
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp:641:22: error: ‘joint_tra_’ was not declared in this scope
     des_joint_pos_ = joint_tra_->getPosition(cur_time);
                      ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp:651:14: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
       delete joint_tra_;
              ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp: In member function ‘void robotis_op::OnlineWalkingModule::initOffsetControl()’:
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp:712:3: error: ‘body_offset_tra_’ was not declared in this scope
   body_offset_tra_ =
   ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp:713:11: error: expected type-specifier
       new robotis_framework::MinimumJerk(ini_time, mov_time,
           ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp: In member function ‘void robotis_op::OnlineWalkingModule::calcOffsetControl()’:
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp:734:24: error: ‘body_offset_tra_’ was not declared in this scope
     des_body_offset_ = body_offset_tra_->getPosition(cur_time);
                        ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp:742:14: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
       delete body_offset_tra_;
              ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp: In member function ‘void robotis_op::OnlineWalkingModule::initFeedforwardControl()’:
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp:1171:3: error: ‘feed_forward_tra_’ was not declared in this scope
   feed_forward_tra_ =
   ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp:1172:11: error: expected type-specifier
       new robotis_framework::MinimumJerkViaPoint(init_time, fin_time, via_time, dsp_ratio,
           ^
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp: In member function ‘void robotis_op::OnlineWalkingModule::setFeedforwardControl()’:
/home/robotis/robotis_ws/src/ROBOTIS-OP3/op3_online_walking_module/src/online_walking_module.cpp:1603:46: error: ‘feed_forward_tra_’ was not declared in this scope
   std::vector<double_t> feed_forward_value = feed_forward_tra_->getPosition(cur_time);
                                              ^
make[2]: *** [CMakeFiles/op3_online_walking_module.dir/src/online_walking_module.cpp.o] エラー 1
make[1]: *** [CMakeFiles/op3_online_walking_module.dir/all] エラー 2
make: *** [all] エラー 2
cd /home/robotis/robotis_ws/build/op3_online_walking_module; catkin build --get-env op3_online_walking_module | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................................................................................................................................
Failed     << op3_online_walking_module:make                [ Exited with code 2 ]                                                                                                             
Failed    <<< op3_online_walking_module                     [ 4.2 seconds ]                                                                                                                    
[build] Summary: 6 of 7 packages succeeded.                                                                                                                                                    
[build]   Ignored:   62 packages were skipped or are blacklisted.                                                                                                                              
[build]   Warnings:  2 packages succeeded with warnings.                                                                                                                                       
[build]   Abandoned: None.                                                                                                                                                                     
[build]   Failed:    1 packages failed.                                                                                                                                                        
[build] Runtime: 6.5 seconds total.                                                                                                                                                            
robotis@ROBOTIS-JAPAN05:~/robotis_ws$

**Comment by kaym9n** [comment]
We updated [ROBOTIS-Math](https://github.com/ROBOTIS-GIT/ROBOTIS-Math) reposirory.
Try agiain please. 

And If you comfile ROBOTIS-Math, you have to follow like below.
```
Required for scilab-optimization package
$ sudo apt-get install scilab
```

**Comment by robograffitti** [comment]
Now build scceeded. Thanks!
